### ISSUE TITLE
Emails constantly rejected by recipient

### ISSUE THREAD

**Issue by MarcHubertHongKong** [Curioo/emailpyspam#23]
Hi there,

Further to several trials sending 50 to 100 emails to a recipient using a gmail address properly configured I got the below rejection message from recipient server:

The response from the remote server was:

550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [HE1EUR02FT003.eop-EUR02.prod.protection.outlook.com] 

Any input on how to improve and bypass detection?

Many thanks.

**Comment by Curioo** [comment]
Are you using a google email address to send the emails out? This might help: you may have been blocked by microsoft. Use the following link to unblock your IP address. If that doesnt work, then it may be because of the recipient. 
[https://sender.office.com/](https://sender.office.com/)
Please let me know if this works.

**Comment by Curioo** [comment]
If that doesnt work, try using a proxy. I might work on implementing some sort of proxy system, but that would require an entire rewrite of the program since the code is old and not well written.
